/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/push/single": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send one message immediately
         * @description Renders the template, sends synchronously and stores a transactional message. The response carries the final status; failures are reported as data, not as an error.
         */
        post: operations["pushSingle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upsertSmtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upsertLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/upload-recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadRecipients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryFailed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify an API key */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a previously sent message */
        get: operations["message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["failures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonNode: Record<string, never>;
        MessageTemplateRequest: {
            name: string;
            /** @enum {string} */
            channelType: "LINE" | "EMAIL";
            subjectTemplate?: string;
            contentPayload: components["schemas"]["JsonNode"];
        };
        ApiResponseMessageTemplateDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MessageTemplateDto"];
        };
        MessageTemplateDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            channelType?: "LINE" | "EMAIL";
            /** @enum {string} */
            templateType?: "EMAIL_HTML" | "LINE_MESSAGES";
            subjectTemplate?: string;
            contentPayload?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CampaignRequest: {
            title: string;
            /** @enum {string} */
            channelType: "LINE" | "EMAIL";
            /** Format: int64 */
            templateId: number;
            /** @enum {string} */
            targetAudienceType: "CSV_LIST" | "LINE_AUDIENCE_GROUP";
            targetAudienceMeta?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            scheduledAt?: string;
        };
        ApiResponseCampaignDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["CampaignDto"];
        };
        CampaignDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** @enum {string} */
            channelType?: "LINE" | "EMAIL";
            /** Format: int64 */
            templateId?: number;
            /** @enum {string} */
            status?: "DRAFT" | "SCHEDULED" | "PROCESSING" | "COMPLETED" | "AWAITING_RESOLUTION" | "RETRYING" | "TERMINATED";
            /** Format: date-time */
            scheduledAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** @enum {string} */
            targetAudienceType?: "CSV_LIST" | "LINE_AUDIENCE_GROUP";
            targetAudienceMeta?: string;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failedCount?: number;
            /** @enum {string} */
            importStatus?: "NONE" | "IMPORTING" | "READY" | "FAILED";
            importError?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TemplatePreviewRequest: {
            params?: {
                [key: string]: string;
            };
        };
        ApiResponseTemplatePreviewDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TemplatePreviewDto"];
        };
        TemplatePreviewDto: {
            /** @enum {string} */
            channelType?: "LINE" | "EMAIL";
            placeholders?: string[];
            subject?: string;
            html?: string;
            text?: string;
            messages?: components["schemas"]["JsonNode"][];
        };
        SinglePushRequest: {
            /** @enum {string} */
            channel: "LINE" | "EMAIL";
            /** Format: int64 */
            templateId?: number;
            templateName?: string;
            recipient: string;
            params?: {
                [key: string]: string;
            };
        };
        ApiResponseSinglePushResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SinglePushResponse"];
        };
        SinglePushResponse: {
            /** Format: int64 */
            messageId?: number;
            /** @enum {string} */
            status?: "PENDING" | "SENT" | "FAILED";
            externalMessageId?: string;
            errorCode?: string;
            errorMessage?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        SmtpChannelRequest: {
            host: string;
            /** Format: int32 */
            port: number;
            username?: string;
            password?: string;
            fromEmail: string;
            fromName?: string;
            sslEnabled?: boolean;
            testRecipient?: string;
        };
        ApiResponseChannelConfigDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ChannelConfigDto"];
        };
        ChannelConfigDto: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            channelType?: "LINE" | "EMAIL";
            lineChannelId?: string;
            hasLineChannelSecret?: boolean;
            hasLineChannelToken?: boolean;
            smtpHost?: string;
            /** Format: int32 */
            smtpPort?: number;
            smtpUsername?: string;
            hasSmtpPassword?: boolean;
            smtpFromEmail?: string;
            smtpFromName?: string;
            smtpSslEnabled?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        LineChannelRequest: {
            channelId: string;
            channelSecret?: string;
            channelAccessToken?: string;
        };
        PublishRequest: {
            /** Format: date-time */
            scheduledAt?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            tenant?: string;
        };
        ApiResponseLoginResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
        };
        LoginResponse: {
            token?: string;
            /** Format: date-time */
            expiresAt?: string;
            user?: components["schemas"]["UserDto"];
            tenant?: components["schemas"]["TenantDto"];
        };
        TenantDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED";
            /** Format: date-time */
            createdAt?: string;
        };
        UserDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            tenantId?: number;
            email?: string;
            /** @enum {string} */
            role?: "ADMIN";
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
            /** Format: date-time */
            createdAt?: string;
        };
        CreateApiKeyRequest: {
            name: string;
        };
        ApiKeyCreatedDto: {
            apiKey?: components["schemas"]["ApiKeyDto"];
            key?: string;
        };
        ApiKeyDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            prefix?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        ApiResponseApiKeyCreatedDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ApiKeyCreatedDto"];
        };
        ApiResponsePageResponseMessageTemplateDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseMessageTemplateDto"];
        };
        PageResponseMessageTemplateDto: {
            items?: components["schemas"]["MessageTemplateDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponsePingResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PingResponse"];
        };
        PingResponse: {
            /** Format: int64 */
            tenantId?: number;
            /** Format: int64 */
            apiKeyId?: number;
        };
        ApiResponseTransactionalMessageDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TransactionalMessageDto"];
        };
        TransactionalMessageDto: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            channelType?: "LINE" | "EMAIL";
            /** Format: int64 */
            templateId?: number;
            recipientIdentifier?: string;
            payloadParams?: string;
            /** @enum {string} */
            status?: "PENDING" | "SENT" | "FAILED";
            errorCode?: string;
            errorMessage?: string;
            externalMessageId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        ApiResponseHealthResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["HealthResponse"];
        };
        HealthResponse: {
            status?: string;
            /** Format: date-time */
            time?: string;
        };
        ApiResponseListChannelConfigDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ChannelConfigDto"][];
        };
        ApiResponsePageResponseCampaignDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseCampaignDto"];
        };
        PageResponseCampaignDto: {
            items?: components["schemas"]["CampaignDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponseCampaignDetailDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["CampaignDetailDto"];
        };
        CampaignDetailDto: {
            campaign?: components["schemas"]["CampaignDto"];
            recipients?: components["schemas"]["RecipientCounts"];
        };
        RecipientCounts: {
            /** Format: int64 */
            pending?: number;
            /** Format: int64 */
            sending?: number;
            /** Format: int64 */
            sent?: number;
            /** Format: int64 */
            failed?: number;
            /** Format: int64 */
            cancelled?: number;
        };
        ApiResponseCampaignStatsDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["CampaignStatsDto"];
        };
        CampaignStatsDto: {
            /** Format: int64 */
            campaignId?: number;
            /** @enum {string} */
            status?: "DRAFT" | "SCHEDULED" | "PROCESSING" | "COMPLETED" | "AWAITING_RESOLUTION" | "RETRYING" | "TERMINATED";
            processing?: boolean;
            /** @enum {string} */
            importStatus?: "NONE" | "IMPORTING" | "READY" | "FAILED";
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failedCount?: number;
            recipients?: components["schemas"]["RecipientCounts"];
            failureBreakdown?: components["schemas"]["FailureBreakdownDto"][];
            /** Format: date-time */
            scheduledAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        FailureBreakdownDto: {
            errorCode?: string;
            /** Format: int64 */
            count?: number;
        };
        ApiResponsePageResponseCampaignRecipientDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseCampaignRecipientDto"];
        };
        CampaignRecipientDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            campaignId?: number;
            recipientIdentifier?: string;
            payloadParams?: string;
            /** @enum {string} */
            status?: "PENDING" | "SENDING" | "SENT" | "FAILED" | "CANCELLED";
            errorCode?: string;
            errorMessage?: string;
            /** Format: int32 */
            retryCount?: number;
            externalMessageId?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        PageResponseCampaignRecipientDto: {
            items?: components["schemas"]["CampaignRecipientDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponseMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
        };
        MeResponse: {
            user?: components["schemas"]["UserDto"];
            tenant?: components["schemas"]["TenantDto"];
        };
        ApiResponseListApiKeyDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ApiKeyDto"][];
        };
        ApiResponseVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
        };
        ApiResponseApiKeyDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ApiKeyDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMessageTemplateDto"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMessageTemplateDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDetailDto"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                channel?: "LINE" | "EMAIL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseMessageTemplateDto"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMessageTemplateDto"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TemplatePreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplatePreviewDto"];
                };
            };
        };
    };
    pushSingle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SinglePushRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSinglePushResponse"];
                };
            };
        };
    };
    upsertSmtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmtpChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseChannelConfigDto"];
                };
            };
        };
    };
    upsertLine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseChannelConfigDto"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: "DRAFT" | "SCHEDULED" | "PROCESSING" | "COMPLETED" | "AWAITING_RESOLUTION" | "RETRYING" | "TERMINATED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCampaignDto"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    uploadRecipients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    retryFailed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    abort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListApiKeyDto"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseApiKeyCreatedDto"];
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePingResponse"];
                };
            };
        };
    };
    message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionalMessageDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseHealthResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListChannelConfigDto"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCampaignStatsDto"];
                };
            };
        };
    };
    recipients: {
        parameters: {
            query?: {
                status?: "PENDING" | "SENDING" | "SENT" | "FAILED" | "CANCELLED";
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCampaignRecipientDto"];
                };
            };
        };
    };
    failures: {
        parameters: {
            query?: {
                errorCode?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCampaignRecipientDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseApiKeyDto"];
                };
            };
        };
    };
}
